# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 01:09
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion
import invoices.models
import uuid


class Migration(migrations.Migration):

    replaces = [('invoices', '0001_initial'), ('invoices', '0002_invoice_uuid'), ('invoices', '0003_invoice_public'), ('invoices', '0004_invoice_description'), ('invoices', '0005_auto_20160223_1125'), ('invoices', '0006_auto_20160223_1132'), ('invoices', '0007_auto_20160223_1133'), ('invoices', '0008_relatedpdf_description'), ('invoices', '0009_auto_20161214_1446'), ('invoices', '0010_remove_hourlyservice_hours')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, invoices.models.ReverseDisplayTotalMixin),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, invoices.models.DisplayTotalMixin),
        ),
        migrations.CreateModel(
            name='FixedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, invoices.models.DisplayTotalMixin),
        ),
        migrations.CreateModel(
            name='HourlyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('hours', models.DecimalField(decimal_places=3, max_digits=11)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, invoices.models.DisplayTotalMixin),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('finalized', models.BooleanField(default=False)),
                ('hourly_services_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fixed_services_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('expense_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('payment_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, invoices.models.ReverseDisplayTotalMixin),
        ),
        migrations.CreateModel(
            name='RelatedPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=invoices.models.uuidUpload, verbose_name='PDF')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('checks_payable_to', models.CharField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Vendor'),
        ),
        migrations.AddField(
            model_name='hourlyservice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
        migrations.AddField(
            model_name='fixedservice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
        migrations.AddField(
            model_name='credit',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterModelOptions(
            name='relatedpdf',
            options={'ordering': ['pdf_order']},
        ),
        migrations.AddField(
            model_name='relatedpdf',
            name='pdf_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='relatedpdf',
            name='invoice',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
        migrations.AddField(
            model_name='credit',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='fixedservice',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='hourlyservice',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='fixedservice',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='hourlyservice',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='relatedpdf',
            name='description',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hourlyservice',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.RemoveField(
            model_name='hourlyservice',
            name='hours',
        ),
    ]
