# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_squashed_0010_remove_hourlyservice_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedpdf',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='relatedpdf',
            name='pdf_order',
        ),
        migrations.AddField(
            model_name='relatedpdf',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.Invoice'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.Invoice'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='fixedservice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.Invoice'),
        ),
        migrations.AlterField(
            model_name='fixedservice',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='hourlyservice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.Invoice'),
        ),
        migrations.AlterField(
            model_name='hourlyservice',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.Client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.Vendor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.Invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='relatedpdf',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
    ]
