# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
