# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:25
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedpdf',
            options={'ordering': ['pdf_order']},
        ),
        migrations.AddField(
            model_name='relatedpdf',
            name='pdf_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='relatedpdf',
            name='invoice',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
    ]
