# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20160223_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='fixedservice',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='hourlyservice',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
