# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20160223_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='fixedservice',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='hourlyservice',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['position']},
        ),
    ]
