# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20160223_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedpdf',
            name='description',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
