# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-14 19:46
from __future__ import unicode_literals

from django.db import migrations, models

from datetime import timedelta
from decimal import Decimal

def convert_to_durations(apps, schema_editor):
    HourlyService = apps.get_model("invoices", "HourlyService")

    for hourly_service in HourlyService.objects.all():
        total_hours = hourly_service.hours
        partial_hours = total_hours % 1
        full_hours = int(total_hours - partial_hours)
        minutes = 0

        if partial_hours == Decimal('.333'):
            minutes = 20
        elif partial_hours == Decimal('.666') or partial_hours == Decimal('.667'):
            minutes = 40
        elif partial_hours == Decimal('-.333'):
            minutes = -20
        elif partial_hours == Decimal('-.666') or partial_hours == Decimal('-.667'):
            minutes = -40
        else:
            minutes = float(partial_hours * 60)

        hourly_service.duration = timedelta(hours=full_hours, minutes=minutes)

        hourly_service.save()

class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_relatedpdf_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyservice',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='hourlyservice',
            name='hours',
            field=models.DecimalField(decimal_places=3, max_digits=11, null=True),
        ),
        migrations.RunPython(convert_to_durations),
    ]
