# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-14 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_auto_20161214_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlyservice',
            name='hours',
        ),
    ]
