# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-25 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_remove_hourlyservice_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedpdf',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
    ]
