# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-25 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20171224_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedpdf',
            options={'ordering': ['position']},
        ),
        migrations.RenameField(
            model_name='relatedpdf',
            old_name='pdf_order',
            new_name='position',
        ),
    ]
