"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import configparser
import email.utils

import dj_database_url

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DATABASE_URL = os.environ["DATABASE_URL"]

DEBUG = bool(os.environ.get('DEBUG', False))
SERVE_STATIC = bool(os.environ.get('DEBUG', False))

MEDIA_ROOT = os.environ['MEDIA_ROOT']
STATIC_ROOT = os.environ['STATIC_ROOT']

MEDIA_URL = os.environ['MEDIA_URL']
STATIC_URL = os.environ['STATIC_URL']

ALLOWED_HOSTS = os.environ['ALLOWED_HOSTS'].split()

STATICFILES_STORAGE = os.environ.get('STATICFILES_STORAGE', 'django.contrib.staticfiles.storage.StaticFilesStorage')

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
SERVER_EMAIL = os.environ.get('SERVER_ADDRESS', 'root@localhost')

ADMINS = [email.utils.parseaddr(a.strip()) for a in os.environ.get('ADMINS', '').split(",")]
MANAGERS = [email.utils.parseaddr(a.strip()) for a in os.environ.get('MANAGERS', '').split(",")]

SECRET_KEY = os.environ['SECRET_KEY']

TIME_ZONE = 'America/New_York'
LANGUAGE_CODE = 'en-US'

DATABASES = {'default': dj_database_url.config(default=DATABASE_URL)}

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'invoices',
    'adminsortable2',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

USE_I18N = True
USE_L10N = True
USE_TZ = True